export { LicenseWebpackPlugin } from './LicenseWebpackPlugin.js';
export { LicensePluginCore } from './LicensePluginCore.js';
export { viteLicensePlugin } from './ViteLicensePlugin.js';
export { normalizeLicense } from './checker/BuiltInLicenseChecker.js';
export type { LicensePluginOptions, OutputFormat, LicensePluginContext } from './LicensePluginCore.js';
export type { LicenseWebpackPluginOptions, OutputFormat as WebpackOutputFormat } from './LicenseWebpackPlugin.js';
export type { PackageInfo } from './model/PackageInfo.js';
export type { LicenseInfo, OutputItem } from './model/LicenseInfo.js';
export type { LicenseBuildReport } from './model/LicenseBuildReport.js';
export type { Recorder } from './Recorder.js';
export { DefaultRecorder } from './Recorder.js';
